### ISSUE TITLE
ModelSVMWrapper

### ISSUE THREAD

**Issue by londere** [Luttik/keras_svm#2]
Hello there, I'm wondering if you use a data generator in this method.

As I understand the data.fit is when you have the labels of the dataset as supervised classification, but what happens when you need an unsupervised classification, that's the need for the usage data.fit.generator.

In advance thanks.

**Comment by Luttik** [comment]
This package replaces the last layer with an SVM after training (which requires another round of training for the SVM). I might be wrong but I don't think this approach really fits for unsupervised learning.

**Comment by londere** [comment]
Well as i do understand stand it could work because you only replace the ann classifier for a svm one as you could change it for a logistic regression or other classifier but the problem should fit the data in my case i do a binary classification as unsupervised one as i know and might be mistaken we could do it that is the reason of the request

**Comment by Luttik** [comment]
Ok, I am not entirely sure if this is just a comment or a change request. But I will close this issue.
